In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [8]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,15,3)

array([ 2,  5,  8, 11, 14])

In [13]:
print(a)


[1 2 3]


In [14]:
a[1]=10


In [21]:
a

array([ 1, 10,  3])

In [22]:
b = a.reshape(len(a),1)
b


array([[ 1],
       [10],
       [ 3]])

In [26]:
print(b)
print(len(b))
len(b[1])

[[ 1]
 [10]
 [ 3]]
3


1

In [27]:
b.reshape(3,)

array([ 1, 10,  3])

In [28]:
b.ndim


2

In [29]:
b


array([[ 1],
       [10],
       [ 3]])

In [32]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(3L, 1L)
3


In [33]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(3L,)
3


In [37]:
l = list([[1,2,3],[4,5,6],"string"])

In [38]:
al = np.array(l)
al


array([list([1, 2, 3]), list([4, 5, 6]), 'string'], dtype=object)

In [39]:
l

[[1, 2, 3], [4, 5, 6], 'string']

In [42]:
lz = np.full((3,5),80)
lz

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [45]:
le=np.eye(4)
le

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
ll=np.linspace(2,4,num=7)
ll

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        ])

In [60]:
ra = np.random.random((3,4)) 
ra

array([[0.08702034, 0.23269072, 0.35346512, 0.27020456],
       [0.0139382 , 0.12517334, 0.88560461, 0.99497285],
       [0.54041518, 0.29176407, 0.14372837, 0.00693796]])

In [61]:
np.max(ra)

0.994972853241872

In [65]:
np.max(ra, axis= 0)

array([0.54041518, 0.29176407, 0.88560461, 0.99497285])

In [67]:
ra = np.random.random((3,4,5)) 
np.max(ra, axis=2)

array([[0.95975877, 0.6156948 , 0.91706277, 0.57135674],
       [0.84219056, 0.84982976, 0.83046848, 0.83317213],
       [0.84045705, 0.75058581, 0.71847719, 0.77197882]])

In [70]:
ra = np.random.random((3,4)) 
ra

array([[0.24294353, 0.1682835 , 0.82140905, 0.23589421],
       [0.25022077, 0.20812672, 0.12356313, 0.83141583],
       [0.91217588, 0.50589764, 0.51854561, 0.31174089]])

In [71]:
ra[1,2]

0.12356313300516097

In [72]:
ra[0:2,:]

array([[0.24294353, 0.1682835 , 0.82140905, 0.23589421],
       [0.25022077, 0.20812672, 0.12356313, 0.83141583]])

In [73]:
ra[:,1:]

array([[0.1682835 , 0.82140905, 0.23589421],
       [0.20812672, 0.12356313, 0.83141583],
       [0.50589764, 0.51854561, 0.31174089]])

In [76]:
ra[:-2,0]

array([0.24294353])

In [77]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [78]:
y
x

array([[1., 2.],
       [3., 4.]])

In [79]:
y

array([[5., 6.],
       [7., 8.]])

In [80]:
x.T

array([[1., 3.],
       [2., 4.]])

In [82]:
x>2

array([[False, False],
       [ True,  True]])

In [89]:
x[x>2]

array([3., 4.])

In [90]:
x[x%2 ==0]

array([2., 4.])

In [91]:
x[x>=1]

array([1., 2., 3., 4.])

In [92]:
x+1

array([[2., 3.],
       [4., 5.]])

In [93]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [94]:
10 * np.sin(x)

array([[ 8.41470985,  9.09297427],
       [ 1.41120008, -7.56802495]])

In [95]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [96]:
xf = x.flatten()
yf = y.flatten()

In [98]:
xf


array([1., 2., 3., 4.])

In [99]:
xf.dot(yf)
#صرب داخلی

70.0

In [100]:
np.matmul(xf,yf) 

70.0

In [101]:
np.linalg.det(x)

-2.0000000000000004

In [102]:
x


array([[1., 2.],
       [3., 4.]])

In [103]:
y

array([[5., 6.],
       [7., 8.]])

In [104]:
np.hstack((x,y))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [105]:
np.vstack((x,y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [109]:
np.vstack((y,x))

array([[5., 6.],
       [7., 8.],
       [1., 2.],
       [3., 4.]])

In [110]:
np.vstack(x)

array([[1., 2.],
       [3., 4.]])